# Generated by Django 2.1.3 on 2021-05-03 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advisor',
            old_name='id',
            new_name='advisor_id',
        ),
    ]
