# Generated by Django 2.1.3 on 2021-05-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0005_auto_20210503_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='id',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
